sequenceDiagram
    participant SP
    participant User (Browser)
    participant IdP
    User (Browser)->>SP: IdP selection
    SP-->>+User (Browser): 
    User (Browser)-->>-IdP: SAML AuthnRequest + AttributeAuthority Extension
    IdP-->>+User (Browser): 
    User (Browser)-->>-IdP: authentication challenge
    IdP->>+SPID Registry: /oidc/list?entity_type=oauth_authorization_server&trust_marked=true
    SPID Registry->>IdP: []
    IdP-->>User (Browser): (skip AA selection and return AuthnResponse)
    User (Browser)-->>SP: AuthnResponse