sequenceDiagram
    participant SP
    participant User (Browser)
    participant IdP
    User (Browser)->>SP: IdP selection
    SP-->>+User (Browser): 
    User (Browser)-->>-IdP: AuthnRequest
    IdP-->>User (Browser): Error